/*
 this is automatically generated by vue create command 
 
 We should probably never have to change anything in here
 
 it is automatically loaded when the vue app is started*/

import Vue from "vue";
import App from "./App.vue";

Vue.config.productionTip = false;

new Vue({ // instantiates a vue application object
  render: (h) => h(App), // render tells vue what the main component is called -- must match name on import
}).$mount("#app"); // #app - the element where the main component is placed
