package com.techelevator.reservations;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// This was generated by the Spring Initializr process

// This IS the server
// We are using the Spring Boot 2 Framework to run and manage our servers
// Spring Boot 2 makes very easy to implement server applications
// So we can focus on the application processing rather infrastructure for a server

// @word is annotation - tells various Java components things they need to know
//     @Test - tells JUnit here comes a unit test
//     @After - tells JUnit do this after every JUnit test
//     @Override - tells Java verify the method is a proper overrode of super class method
//     @Autowired - Tells Spring to automatically instantiate an object and assign to a reference

@SpringBootApplication  // Tells Spring Boot this class contains a Spring Boot server
public class HotelReservationsApplication {

    public static void main(String[] args) {
        // Tell Spring Boot to run this method with these arguments to start the server
        //                   (class that defines the server(this one), any-arguments-to-pass-to-server
        SpringApplication.run(HotelReservationsApplication.class, args);
    }

}
